name: .NET WPF Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Release]

    env:
      Solution_Name: numoeminformations.sln
      Configuration: ${{ matrix.configuration }}

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
    - run: dotnet build numoeminformations/numoeminformations.csproj -c $env:Configuration -r win-arm64
      shell: pwsh

    - name: Upload Avalonia App
      uses: actions/upload-artifact@v7
      with:
        name: App
        path: numoeminformations/bin/Release/net10.0-windows10.0.26100.0
        include-hidden-files: true
        if-no-files-found: error
